try{window.ibLoginOrchHost='https://unauthib.anz.com'
window.ibLoginHandoverHost='https://banking5.anz.com'
window.loginSuccessPath='/'
window.loginSuccessDomain='.anz.com'
window.loginSuccessSecure='true'
window.loginSuccessMaxAge='60'
window.loginSuccessRedirectURL='https://banking5.anz.com/IBUI/#/login'
window.ibCroURL='https://www.recovery.anz.com/recover/do-you-know-your-crn?target=host1'
window.registrationSpaURL='https://register.anz.com/internetbanking'
window.plannedMaintenanceFlag='false'
window.maintenancePara1='We are working to have ANZ Internet Banking available again as soon as possible.'
window.maintenancePara2='For alternative banking needs please use:'
window.maintenanceListItems='[{"text":"ANZ Phone Banking 13 13 14 (International +61 3 9683 9999)","phoneNumber":"13 13 14","businessNumber":"+61 3 9683 9999"},{"text":"ANZ App (if already registered)"}]'
window.ctiSnippetServerName='ctmdx.anz.com'
window.aps910Flag='false'
window.publicKey='-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhAC0qrxqg2XdK+h7gfMZoUQAXg0xO47p4NVLEoVUyWtHGB4ao7hBwe5gNAOEyze7q4BiAYNGaHnkWeEATAxzcbWP8R7cV+DZcJVmZAGhsL00hyAK/7SUVutvT0Aup1DVlG5YZeId+5lB9YKVHQ5WoSpT5mNVcfyoEGDNX66IvqFPSSiGgaITi0fpwfsX+w6b3hF0+U0//cjvwaOlldrlE+ED3O93zNul5zYB3upFNghFW1gGF5rAIzzj860LmWNKgXKSJenFTNMgaq8jBdGshdEhPCfin5CSKH84NHKAY986cVE6d+AyE9E09lzkRlBn8R8PLalhlmmXjZqCJgpomQIDAQAB-----END PUBLIC KEY-----'
window.kid='anzid-token-signer'}catch(e){window.ibLoginOrchHost=''
window.ibLoginHandoverHost=''}